# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180312_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(default=1, verbose_name=b'rating value')),
                ('comment', models.TextField(max_length=300, verbose_name=b'Comments about book')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Book', verbose_name=b'book details')),
                ('review_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Reader', verbose_name=b'review_by')),
            ],
            options={
                'verbose_name': 'Book Review',
            },
        ),
        migrations.AlterUniqueTogether(
            name='bookreview',
            unique_together=set([('review_by', 'book')]),
        ),
    ]
