# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_reader_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='uuid',
            field=models.CharField(db_index=True, default='asadsa', editable=False, max_length=40, unique=True, verbose_name=b'UUID'),
            preserve_default=False,
        ),
    ]
