# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_reader_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookOverAllRating',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('total_sum', models.FloatField(verbose_name=b'Total Sum')),
                ('total_count', models.PositiveIntegerField(verbose_name=b'Total Rating Count')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Book')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
