# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_bookoverallrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookoverallrating',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Book', verbose_name=b'Book'),
        ),
        migrations.AlterField(
            model_name='bookoverallrating',
            name='total_count',
            field=models.PositiveIntegerField(default=0, verbose_name=b'Total Rating Count'),
        ),
        migrations.AlterField(
            model_name='bookoverallrating',
            name='total_sum',
            field=models.FloatField(default=0.0, verbose_name=b'Total Sum'),
        ),
    ]
